### ISSUE TITLE
Milestone 1: Recommendation Model and First Deployment

### ISSUE THREAD

**Issue by danyatingshen** [danyatingshen/Group3-Movie-Recommandation-System#1]
#### Part one: 
- [x] 2/13: Set up VM, GitHub, and flask project -> BE working "hello world " @danyatingshen @sakshik-cmu 
- [x] 2/13: DATA - Collect data, API, user + movie @vinwizardtoo 
- [x] 2/13: DATA - Clean + parse + future Eng @vinwizardtoo 
- [x] 2/15: ML Service -> train ML algo with the input data 
- [x] 2/15: ML Service -> deploy this service Working API 
#### Part two: 
- [x] 2/13: Build a connection with Kafka @danyatingshen @sakshik-cmu 
- [x] 2/13: Process input from Kafka @danyatingshen @sakshik-cmu 
- [x] 2/17: call ML for output 
- [x] 2/17: responded with formatted data 
#### Report: 
- This milestone is worth 100 points:

#### Summary Report (15/2/2023): 
 - [x] 10pt: The report contains a description of the data used and the learning technique selected. The text explains why this approach was chosen. The described chosen approach matches the problem.
 - [x] 10pt: A link to the implementation of the learning step is provided. The implementation matches the description and addresses the learning problem.
- [x]  5pt each (up to 20pt): The report describes metrics of the four qualities explicitly in the three steps: metric, data, and operationalization. The description is clear and sufficient to independently measure the quality. A pointer to implementation of each measurement is provided. The results of the measure are reported and match to the metric description and the models.
- [ ]  10pt: The report argues which of the compared models should be used in production.
- [ ]  10pt: The report contains a description of the prediction service and explains how a ranking is computed.
- [x]  10pt: A link to the implementation of the prediction service is provided. The implementation matches the description.
- [x] #10
- [x]  10pt: The prediction services successfully answers at least 2000 recommendation requests in the 24 hours before or after submission. To be successful, the answer must be well-formed and arrive within the time limit. (We use the status 200 message in the movielog for grading).
- [x]  10pt: The prediction service answers at least 10% of all recommendation requests in the 24 hours before or after submission with personalized recommendations (i.e., 200 status, not the same recommendation for every user).
- [x]  3pt (individually): The teammaker survey (on Catme) is filled out.
- [x]  3pt (individually): The teamwork survey for this milestone is filled out.
- [x]  3pt: Bonus points for social activity (see very end of this document)
