### ISSUE TITLE
Milestone 2 (March 13th)

### ISSUE THREAD

**Issue by vinwizardtoo** [danyatingshen/Group3-Movie-Recommandation-System#20]
- [ ] Online Evaluation and Offline Evaluation  @danyatingshen @vinwizardtoo 
  - [ ]  
- [ ] Pipeline and overall testing tasks @Pavitra-kadiyala @sakshik-cmu @sumeetshinde7 
  - [ ] Data Quality @sumeetshinde7 
  - [ ] Pipeline Integration and Testing @Pavitra-kadiyala 
  - [ ] Continuous Integration  @sakshik-cmu 
 

=================================================================================================

- [ ] 10pt: Most commits (>60%) are reasonably cohesive and contain reasonable commit messages. The code is generally reasonably well structured and understandable.
- [ ] 10pt: The report describes how the pipeline is implemented and structured and contains a pointer to the pipeline implementation. The implementation matches the description.
 - [ ] 15pt: Data quality checks are described in the report and implemented (with a link to the implementation provided). The description matches the implementation. At a minimum, schema violations in inputs are detected and handled and strong data drift is detected.
 - [ ] 15pt: A suitable strategy for offline model evaluation is described in the report that covers (1) validation/test split, (2) a clear 3-step description of the used metric, and (3) a plausible justification of why the metric is suitable for the problem and avoids common pitfalls. A link to a corresponding implementation that matches the description is provided. Offline evaluation results are included or linked for the used model that were computed with the described process and metric.
 - [ ] 20pt: A suitable strategy for online model evaluation is described in the usual three step format: (1) the model accuracy metric used, (2) the telemetry data collected, and (3) how the metric is computed from the data. A link to a corresponding implementation that matches the description is provided. Online evaluation results that were computed with the described process and metric are included or linked.
 - [ ] 20pt: A description of how the pipeline was tested is included in the report and a link to the corresponding tests is included. The report argues why the performed testing was adequate. A coverage report is included or linked.
 - [ ] 10pt: The infrastructure tests are all automated with a continuous integration service and triggered automatically when code is changed on GitHub. A pointer to the service is provided.
 - [ ] 3pt (individually): The teamwork survey for this milestone is filled out.
 - [ ] 5pt: Bonus points for using pull requests and conducting code review within those pull requests for the majority of changes. A brief description of the process is included in the report.
- [ ] 3pt: Bonus points for social activity (see very end of this document)
