### ISSUE TITLE
Milestone 1-Build a model inference service

### ISSUE THREAD

**Issue by danyatingshen** [danyatingshen/Group3-Movie-Recommandation-System#8]
Master issue: 
### Task summary: https://github.com/danyatingshen/Group3-Movie-Recommandation-System/issues/1

Build a model inference service that provides movie recommendations on request given your learned model (e.g. using flask). Specifically, we will send http calls to http://<address-of-your-virtual-machine>:8082/recommend/<userid> to which your service should respond with an ordered comma-separated list of up to 20 movie IDs in a single line, from highest to lowest recommendation. We will wait for answers to our requests for at most 800ms. You can recognize whether your response has been correctly received and parsed by a corresponding log entry in the Kafka stream (expect to see an entry <time>,<userid>, recommendation request <server>, status <200 for success>, result: <parsed recommendations>, <responsetime>).

Step: 
- [x] Create a working flask basic service: https://github.com/danyatingshen/Group3-Movie-Recommandation-System/pull/4
- [x] Deploy to VM: see doc under `VM operation and Kafka` session 
- [x] Serve the service on VM and make it externally available: https://github.com/danyatingshen/Group3-Movie-Recommandation-System/pull/5
- [x] Add get recommendation API call: https://github.com/danyatingshen/Group3-Movie-Recommandation-System/pull/7
- [x] Read from Kafka 
- [ ] Write back to Kafa

**Comment by sakshik-cmu** [comment]
Write back to Kafka: Not required
